/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComparisonSlider: typeof import('./src/components/ComparisonSlider.vue')['default']
    IconSolarCloudLinear: typeof import('~icons/solar/cloud-linear')['default']
    IconSolarGalleryLinear: typeof import('~icons/solar/gallery-linear')['default']
    IconSolarMagniferLinear: typeof import('~icons/solar/magnifer-linear')['default']
    IconSolarRocket2Linear: typeof import('~icons/solar/rocket2-linear')['default']
    IconSolarSettingsLinear: typeof import('~icons/solar/settings-linear')['default']
    IconSolarUploadSquareBroken: typeof import('~icons/solar/upload-square-broken')['default']
    IconSolarWidgetLinear: typeof import('~icons/solar/widget-linear')['default']
  }
}
